### ISSUE TITLE
Module content is stored in temporary folder

### ISSUE THREAD

**Issue by ss23** [silverstripe/addons.silverstripe.org#102]
The live addons site has addon content checked out to `/tmp/silverstripe-cache-sites-addons..... /addons/add-ons/username/project`.
This is bad because 
- /tmp is often tmpfs so this will use up space
- /tmp is cleared on reboot (on Debian at least) which takes a long time to do with this many individual files
- If people are using a release structure with a release per folder (like we are), then each release loses the content for the addon.

Instead, we should probably have a separate place to put it that isn't in the release folder itself, but separate so different releases of the site can access it.
Suggest a `define` in _ss_envrionment that defaults to `/var/tmp/addons-*hash*/` or similar if nothing is defined.

**Comment by robbieaverill** [comment]
I believe that source code is now stored in `addons-downloads/` in the root. It's not a shared directory on SSP, so will persist across deployments and is not considered as temporary.
