### ISSUE TITLE
Add comments

### ISSUE THREAD

**Issue by chillu** [silverstripe/addons.silverstripe.org#11]
I would suggest we simply use Disqus, since we already use it on api.ss.org and doc.ss.org. Ask Ingo about setup, we already have an account there.

**Comment by robbieaverill** [comment]
@chillu the comments don't seem to get used any more - should we take them out again?

**Comment by chillu** [comment]
Is there any maintenance overhead with this? Seems like an easy way to allow for more interactivity on addons. Granted, the latest comment was four years ago haha. But unless the existing stuff creates friction, I'm inclined to keep it around. We want to get more into ratings and surfacing popular modules, maybe those discussions help with that?

**Comment by robbieaverill** [comment]
No, no maintenance overhead, just wondering. Let's leave it!

**Comment by chillu** [comment]
Maybe we should just set the expectation that the comments aren't monitored, and that specific questions about the module operation are best placed on the module's issue tracker. I'm not too fussed about keeping comments either way.
