### ISSUE TITLE
Error running composer install --no-dev

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/addons.silverstripe.org#111]
Failed to download ajshort/silverstripe-elastica from source: Failed to clone git@github.com:chillu/silverstripe-elastica.git via git, https, ssh protocols, aborting.

- git://github.com/chillu/silverstripe-elastica.git
  Cloning into 'elastica'...
  fatal: remote error: 
    Repository not found.

- https://github.com/chillu/silverstripe-elastica.git
  Cloning into 'elastica'...
  remote: Repository not found.
  fatal: repository 'https://github.com/chillu/silverstripe-elastica.git/' not found

- git@github.com:chillu/silverstripe-elastica.git
  Cloning into 'elastica'...
  ERROR: Repository not found.
  fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.

    Now trying to download from dist

**Comment by dhensby** [comment]
Well, that's strange that it's trying to download from chillu because it's hosted on silverstripe-australia :/

**Comment by dhensby** [comment]
@chillu weird, this composer points specifically at your repo which it looks like you deleted :/

**Comment by chillu** [comment]
@SpiritLevel @dhensby https://github.com/silverstripe/addons.silverstripe.org/pull/113.

Aside: I've talked to @camfindlay, there's minimal maintenance on this module, partially because it runs a different stack to our usual implementations (elasticsearch instead of solr, resque instead of queuedjobs). There's talk about switching those dependencies.

**Comment by SpiritLevel** [comment]
Thanks @chillu. I'll try installing again :) If I can help with switching over dependencies, let me know. Happy to do the tedious jobs as a way to get more familiar with things.

**Comment by SpiritLevel** [comment]
And, perhaps it would be good to deal with addons.silverstripe.org/pull/110 at the same time ?

**Comment by dhensby** [comment]
should work now I merged #113

**Comment by SpiritLevel** [comment]
Addons installs fine now, except for message that package dflydev/markdown is abandoned, as noted in #110. Thanks guys.

**Comment by chillu** [comment]
@SpiritLevel Yeah very happy for you to help switch things over. Maybe start with the search implementation? We're using https://github.com/silverstripe-labs/silverstripe-fulltextsearch for most of our other projects. It'll mainly be work around replacing search logic in `AddonsController->Addons()`, as well as the index definitions currently located in `Addon`

**Comment by SpiritLevel** [comment]
@chillu Cool. I first have some things to do for docs over the weekend. Then I'll start on addons early next week :) Talk to you soon, after I have had a good look at fulltextsearch. D.
