### ISSUE TITLE
dflydev/markdown deprecated and needs replacing

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/addons.silverstripe.org#115]
Need to replace deprecated dflydev/markdown with michelf/php-markdown (see composer.json).

See silverstripe/addons.silverstripe.org/pull/110.

**Comment by robbieaverill** [comment]
I think generally speaking that [erusev/parsedown](https://github.com/erusev/parsedown) has taken over as the go-to PHP markdown parser. Perhaps this should be the replacement? We should also consider that whichever we choose should ideally be consistent across all of our community sites.

The silverstripe/docsviewer module uses parsedown.

**Comment by robbieaverill** [comment]
The new consensus is to use the GitHub API to render markdown instead.
