### ISSUE TITLE
Double on releases: show released version under "Newest Releases"

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/addons.silverstripe.org#128]
When a new version is released twice, shortly after each other, the module shows up twice in the Newest Releases.
I don't think that should happen.
<img width="489" alt="screen shot 2016-04-21 at 19 54 57" src="https://cloud.githubusercontent.com/assets/680570/14701796/20c8cfd4-07fb-11e6-8126-d19cd49beb98.png">

**Comment by dhensby** [comment]
Well, it has been updated twice.... This is an enhancement imo

**Comment by robbieaverill** [comment]
Maybe we should show the version that was released - it would avoid any ambiguity

**Comment by dhensby** [comment]
yep

**Comment by robbieaverill** [comment]
Updated title

**Comment by dhensby** [comment]
it would probably be nicest if we just had one line per module and showed their releases as a comma separated list
