### ISSUE TITLE
Base popularity on monthly installs instead of total

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/addons.silverstripe.org#130]
Right now, the total installs is the key on the position of a module. I think a monthly total would be a fairer way to go.
Also, the list would become a bit more dynamic, since the current top 10 is so far ahead of other modules, new modules have pretty much 0 chance of appearing, even though they might've been downloaded 10.000 times last month.

**Comment by dhensby** [comment]
A monthly total seems a bit unfair too and a bit too changeable. Couldn't we use some kind of algorithm that gave less importance to old installs? Looks like it could be a case for machine learning :P

How are these stats gathered? Through Packagist?

**Comment by Firesphere** [comment]
As far as I can see, it gathers the totals from packagist and puts the highest download at the top.
So, monthly downloads is indeed not the perfect way, but I think it's more fair than total downloads, until we come up with some algorithm that has an even fairer calculations.
Right now, the top downloads won't change at all, and it will take a new module 10 years to reach the height. Monthly downloads is at least a bit fair. It's unfair to the top-downloads maybe, but I think, those that are really top downloads, will stay at the top 10?

**Comment by Firesphere** [comment]
What if a module is downloaded 10 million times because it was awesome to use for SS3.1, but deprecated in 3.2 and not maintained? It will stay at the top for a long time, just because of that total.

**Comment by dhensby** [comment]
> What if a module is downloaded 10 million times because it was awesome to use for SS3.1, but deprecated in 3.2 and not maintained? It will stay at the top for a long time, just because of that total.

Does that negate the fact it's the most popular?

**Comment by Firesphere** [comment]
It's not the most popular anymore, after that spike, it _was_ the most popular.
I understand going just for monthly isn't the best solution either, but I think it's fairer.

**Comment by Firesphere** [comment]
Okay, what would you think of "most popular" being "total downloads divided by the time it's on packagist", so most popular, becomes based on the total average daily downloads.

**Comment by dhensby** [comment]
seems fairer, yes

**Comment by Firesphere** [comment]
I'll see if I can come up with something that kinda does that fairer method and see what happens?

**Comment by dhensby** [comment]
sure think

**Comment by robbieaverill** [comment]
@Firesphere does #147 resolve this?

**Comment by robbieaverill** [comment]
Resolved by #147
