### ISSUE TITLE
Renamed Modules

### ISSUE THREAD

**Issue by nglasl** [silverstripe/addons.silverstripe.org#133]
The following module was renamed quite a while ago, from http://addons.silverstripe.org/add-ons/nglasl/silverstripe-adminwesome, to http://addons.silverstripe.org/add-ons/nglasl/silverstripe-descriptive, and the old packagist entry removed (rather than abandoned, as it was not a commonly used module).

I want to delete this old reference, however this doesn't seem possible. Is it plausible the newly introduced task from https://github.com/silverstripe/addons.silverstripe.org/issues/29 is not triggering correctly?

**Comment by nglasl** [comment]
Would there happen to be any update on this?

**Comment by dhensby** [comment]
@camfindlay ?

**Comment by camfindlay** [comment]
I'll have to remove this manually. Are you happy for me to do this @nglasl ?

**Comment by nglasl** [comment]
Please :)

**Comment by dhensby** [comment]
@camfindlay ^

**Comment by camfindlay** [comment]
@nglasl old module removed from addons.

**Comment by nglasl** [comment]
Thank you very much, greatly appreciated :)
