### ISSUE TITLE
HelpfulRobot not picking up .scrutinizer.yml

### ISSUE THREAD

**Issue by sunnysideupdevs** [silverstripe/addons.silverstripe.org#137]
https://helpfulrobot.io/sunnysideup/ecommerce_countries
the above URL reportd '"has_scrutinizer_file":false even
though the repo has a .scrutinizer.yml - what is the cause of this?

repo is at:
https://github.com/sunnysideup/silverstripe-ecommerce_countries

**Comment by dhensby** [comment]
cc @helpfulrobot

**Comment by camfindlay** [comment]
unsure on this one.

**Comment by robbieaverill** [comment]
@sunnysideupdevs - now reports `"has_scrutinizer_file":1` - still a problem?
