### ISSUE TITLE
Clean up abandoned modules

### ISSUE THREAD

**Issue by chillu** [silverstripe/addons.silverstripe.org#138]
http://addons.silverstripe.org/add-ons/simonwelsh/gridfieldrelationhandler
http://addons.silverstripe.org/add-ons/silverstripe/gridfield-relation-handler
http://addons.silverstripe.org/add-ons/simonwelsh

These modules have been marked as abandoned in Packagist (https://packagist.org/packages/simonwelsh/gridfieldrelationhandler) and should be either excluded from search results, or clearly marked so in our addons listings as well

**Comment by robbieaverill** [comment]
Excluded or marked as abandoned? I'd lean towards excluding them. People can always find abandoned packages through either Packagist or GitHub, but we possibly shouldn't encourage it by showing them in the addons site...

**Comment by dhensby** [comment]
for these abandoned modules the code is gone - so deletion is best.
