### ISSUE TITLE
SS3 modules show up in SS4 compatibility filter

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/addons.silverstripe.org#151]
Unless there's 96 pages of SS4 compatible modules already, I think there's a bug in the version filtering.

http://addons.silverstripe.org/add-ons?search=&type=&compatibility%5B%5D=4.0

**Comment by robbieaverill** [comment]
It looks like incorrect constraints are being added to the module data before it gets indexed in elasticsearch.

**Comment by robbieaverill** [comment]
There was some dodgy business happening when comparing the module's framework requirement constraints against another constraint created for each SilverStripe version. I've replaced this with a Semver class check using the module's constraint instance against a _string version_ of the SilverStripe framework version, and added some unit tests.

Most worrying - any modules that specify `>=3.1` for the framework will match 4.0 as well!! Hopefully the fixed search filter will show these up :)

**Comment by dhensby** [comment]
sounds like @helpfulrobot could help us open issues/PRs against modules that claim 3.1+ compat without saying <4

**Comment by assertchris** [comment]
Indeed, I'll work something up in a day or two...

**Comment by robbieaverill** [comment]
Something along the lines of:

> Warning! Your framework/CMS composer constraint is [...]. This means that people using silverstripe 4 may accidentally be able to use it. I suggest you use a more specific constraint, here's a pull request that will require any version above x.x, but lower than 4.

**Comment by dhensby** [comment]
just `^[current version]` to replace `>=[current version]` would work, I think
