### ISSUE TITLE
Search for "Compatible silverstripe versions" = 4.0 shows too many results

### ISSUE THREAD

**Issue by sminnee** [silverstripe/addons.silverstripe.org#158]
http://addons.silverstripe.org/add-ons?search=&type=&compatibility%5B%5D=4.0&sort= is listing more modules than it should.

As a specific example, http://addons.silverstripe.org/add-ons/silverstripe/spamprotection is listed but has no 4.0-compatible version.

**Comment by robbieaverill** [comment]
I think we fixed this (#151) in #153 - maybe it hasn't been deployed yet

**Comment by sminnee** [comment]
Right, yeah — it looks like we're due a deploy...
