### ISSUE TITLE
RFC: Module support: >= interpreted as ^

### ISSUE THREAD

**Issue by sminnee** [silverstripe/addons.silverstripe.org#160]
I've been thinking about the module support question as relates to our search.

When someone has set their framework/cms dependency as ">=3.1.0" there are a few possible options:

 * The module maintainer made a mistake
 * The module maintainer, and lo and behold, it worths with both SS3 and SS4. Given renaming this is unlikely, but it might be more likely in future, e.g. "works with SS4 and SS5"
 * The module maintainer has worked to guarantee that it will work with all future versions.

Even if the 2nd option might be the case, the 3rd option is so unlikely that we can ignore it.

As such I think we can afford to deprecate the use of `>=` in our community, instead favouring more explicit multi-version statements such as `^3.1.2 || ^4`.

That being the case, I think we can safely interpret `>=` as `^` when checking compatibility with SilverStripe versions.

**Comment by sminnee** [comment]
@tractorcow @robbieaverill what do you think?

**Comment by robbieaverill** [comment]
>As such I think we can afford to deprecate the use of `>=` in our community, instead favouring more explicit multi-version statements such as `^3.1.2 || ^4`.

Yeah, I think this is generally how people use the contraints at the moment anyway (at least using a caret rather than greater-than

> That being the case, I think we can safely interpret `>=` as `^` when checking compatibility with SilverStripe versions.

I'm torn about this - on the one hand, yes, it's likely to be 99.9% true that modules using this should be using a caret instead, but on the other hand in terms of semver it's actually correct. This means that composer may install a module like this in a SS4 project in theory, and we should perhaps just proactively discourage using these constraints?

We could always do both.

**Comment by sminnee** [comment]
> we should perhaps just proactively discourage using these constraints?

Yeah, we could have a warning like "this might work on SS4 but we don't know" on the detail page of the add-on. But if we show these modules to users searching for SS4-compatible modules, we're doing them a disservice in my opinion.

**Comment by robbieaverill** [comment]
That's definitely true in the context of filtered search

**Comment by dhensby** [comment]
The priority should be to make sure that the addons site is useful. If that means a misinterpreting  `>=` then maybe we should accept that.

However, there seems to be greater issues at play here - when I go to http://addons.silverstripe.org/add-ons?search=&type=&compatibility%5B%5D=4.0&sort= I see the spamprotection module but none of the composer constraints for that module say `>=`, so we're clearly getting false positives regardless of the `>=` usage or not.

It may turn out that there aren't that many modules claiming `>=` and so the problem may be solved somewhere else...

**Comment by robbieaverill** [comment]
Yeah currently the site is reporting all modules as compatible with every version. This is fixed but not deployed yet as far as I know.

I agree re: making an exception to better suit the site's purpose.

**Comment by sminnee** [comment]
> It may turn out that there aren't that many modules claiming >= and so the problem may be solved somewhere else...

The staging server provides an accurate view and there are a few hundred such modules. The more popular modules will likely get some PRs to correct them, but the long tail of rarely used / abandoned modules are unlikely to have those PRs merged, so it's a less viable solution.

**Comment by dhensby** [comment]
Ok, cool so we agree that it's a feature of the songs sure that `>=` is interpreted as `^`

Do we need to think in detail about `>`, `<` and `<=`?

**Comment by robbieaverill** [comment]
I don't think so - `>=` is definitely the problem area, and also the most commonly used out of those examples.

**Comment by robbieaverill** [comment]
Will be deployed with the 2.3.0 release in the morning. Thanks Sam!
