### ISSUE TITLE
Helpfulrobot broken

### ISSUE THREAD

**Issue by sminnee** [silverstripe/addons.silverstripe.org#172]
It looks like the upstream service supplying the helpfulrobot data, is broken. As I understand it, http://helpfulrobot.io/silverstripe/framework, for example, should return JSON, but isn't.

The current addons.silverstripe.org site has a lot of historic data from helpful robot still stored, but new modules don't have anything.

Notably, I've been working on a migration to a new server and that would require re-fetching all the helpful robot data, but it won't be able to do this.

**Comment by robbieaverill** [comment]
I've created a replacement for this at https://github.com/creative-commoners/moduleratings with a Composer plugin to allow easy local runs at https://github.com/creative-commoners/moduleratings-plugin

Will look at adding it to the addons site at some point soon ish

**Comment by robbieaverill** [comment]
I'm going to have a look at implementing this on Friday

**Comment by sminnee** [comment]
Do you think this is a blocker for moving addons to SSP via my other PR, or should we do that in parallel?

**Comment by robbieaverill** [comment]
I think they're mutually exclusive, but could easily ship together

**Comment by robbieaverill** [comment]
Will be rolled out with a new system in place, see #178 

New API needs to be added for GET on a module's ratings metrics - see #180
