### ISSUE TITLE
Readme is not being populated on select repositories

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/addons.silverstripe.org#174]
http://addons.silverstripe.org/add-ons/silverstripe/tagfield

No Readme is showing for this, and other, modules.

Perhaps the background task isn't rebuilding the readme files, or perhaps it's failing at some stage.

**Comment by andrewandante** [comment]
Doesn't seem to have been fixed with the closure of #175, so still needs some attention. AFAICT this is done via the BuildAddonsTask, so maybe that one is failing while the UpdateAddonsTask is succeeding.

**Comment by raissanorth** [comment]
I have noticed the same for https://github.com/tractorcow/silverstripe-proxy-db. The GitHub repo has a README.md, but the information is not displayed on addons https://addons.silverstripe.org/add-ons/tractorcow/silverstripe-proxy-db

**Comment by robbieaverill** [comment]
This should be fixed now, will reopen if we spot it again. Most recent fix was to fix a PHP fatal error in the build job which was preventing anything from building. Just testing the SS4 migration and things are building nicely, so closing for now.

**Comment by AlexStack** [comment]
Hi, same issue, README.md does not display on the page:
https://addons.silverstripe.org/add-ons/alexstack/silverstripe-custom-page-with-contact-us-form
https://addons.silverstripe.org/add-ons/alexstack/silverstripe-custom-carousel-slider

**Comment by brynwhyman** [comment]
Thanks for the report @AlexStack - reopening this issue.

**Comment by robbieaverill** [comment]
Both those repositories now have built readme information.

Ops reported last week (I think) that the server for addons was running out of disk space, so they increased its capacity. That was probably the issue for this. Closing again...
