### ISSUE TITLE
New Addons will not be displayed.

### ISSUE THREAD

**Issue by ArminEden** [silverstripe/addons.silverstripe.org#175]
It seems that new addons will not be added anymore.

created a git repo and added the addon to packagist, but it does not appear under addons.silverstripe.org.

Github of the project:
https://github.com/nomidi/silverstripe-webp-image
Packagist of this project:
https://packagist.org/packages/nomidi/silverstripe-webp-image

It seems that the last "new" addon is from beginning of december.

**Comment by dhensby** [comment]
possibly related to #174

**Comment by andrewandante** [comment]
FYI after logging in as an admin, I see this:

```
[User Error] Uncaught RuntimeException: The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly
GET /dev/tasks?isDevtoken=7b4f2b533510585617f16a4f08c6f6d4&isDev=1
Line 648 in /sites/addons/releases/20171105202652/vendor/composer/composer/src/Composer/Factory.php
```

So it looks like an env_var is missing. Stack trace leads back to BuildAddOnsTask

**Comment by andrewandante** [comment]
Ah, that might just be a web thing. Looks like Redis had stopped, I kicked it and ran the task via CLI and things seem to be churning.

**Comment by robbieaverill** [comment]
Nice!

**Comment by andrewandante** [comment]
@ArminEden looks like your package is there now - I think this was a server-side problem. We might look into non-resque ways to run the task, but for now the problem is remedied.

**Comment by ArminEden** [comment]
Thank you. 
Indeed it is solved for now. :)
