### ISSUE TITLE
Move to stable crontask 1.2 once it's released

### ISSUE THREAD

**Issue by sminnee** [silverstripe/addons.silverstripe.org#177]
Once this is done https://github.com/silverstripe/silverstripe-crontask/issues/46, update composer.json to not use the dev branch.

**Comment by dhensby** [comment]
In the future, the team should use something like `^1.2` even if there is no 1.2 release yet as it'll hook onto 1.x-dev and then stabilise once the release is made.

**Comment by dhensby** [comment]
oh, that's what you did have (https://github.com/silverstripe/addons.silverstripe.org/commit/6d4cc87dca497d37adbfcd9bb6656c22757843ee) maybe the alias wasn't matching 1.x - 1.2.x ?

**Comment by robbieaverill** [comment]
1.2.0 stable is out now

**Comment by robbieaverill** [comment]
PR at #182
