### ISSUE TITLE
Remove "Software" menu item white text-shadow

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/addons.silverstripe.org#186]
>hey team, there’s a wee styling issue on https://addons.silverstripe.org/ ‘Software’ in the nav has a white shadow that needs to be removed pls! Thanks

- Dani, Communikats

View issue here https://addons.silverstripe.org/add-ons

![image](https://user-images.githubusercontent.com/5170590/39972361-b2b9a424-5761-11e8-94f8-204473c1a18a.png)

**Comment by clarkepaul** [comment]
I don't see this issue anymore (I raised it originally). I presume its been fixed?

**Comment by clarkepaul** [comment]
Ignore my previous comment, the issue still exists here https://addons.silverstripe.org/add-ons
