### ISSUE TITLE
Errors in jobs not going to Raygun

### ISSUE THREAD

**Issue by sminnee** [silverstripe/addons.silverstripe.org#187]
The production install was showing this in the update addons task:

```
ERROR [User Error]: Uncaught Error: Call to a member function getTotal() on null
IN GET /dev/tasks/ProcessJobQueueTask
Line 152 in /var/www/mysite/releases/.../mysite/code/services/AddonUpdater.php
```

These errors aren't being sent anywhere useful. Errors should probably be getting sent to Raygun.

**Comment by robbieaverill** [comment]
Oh, we don't have raygun on this site yet. Switched to an enhancement, will add now
