### ISSUE TITLE
Environment checks, pingdom uptime monitoring setup

### ISSUE THREAD

**Issue by chillu** [silverstripe/addons.silverstripe.org#19]
- [ ] Test HTTP connection to packagist.org, ensure we can retrieve a valid JSON file
- [ ] Check that homepage displays some module links
- [ ] Check that detail page for a popular module renders
- [ ] Check that search returns at least one result
- [x] Add site to pingdom (under SS Ltd. account)-
- [ ] Set up error emails to the usual suspects

Note: Use https://github.com/silverstripe-labs/silverstripe-environmentcheck

**Comment by robbieaverill** [comment]
Since the site is on SilverStripe Platform now, we have some automated monitoring tools available through that. We've also installed a custom Raygun logger so can use that for error checking.
