### ISSUE TITLE
Cannot save changes to silverstripe/graphql module

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/addons.silverstripe.org#198]
Trying to save changes to this module in the CMS, I receive an error toast message and a `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT` as well as `502`s and `504`s responses.

**Comment by robbieaverill** [comment]
Debugging info:

* Content area contains some images which fail to load
* Save button response is 403
* Problem looks related to CloudFlare

Network response headers:
```
cf-ray: 42a7a88e8ddc18f0-AKL
content-encoding: br
content-type: text/html; charset=UTF-8
date: Wed, 13 Jun 2018 21:30:28 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
status: 403
x-frame-options: SAMEORIGIN
```

Response body is a captcha form from CloudFlare.

**Comment by robbieaverill** [comment]
@jakedaleweb do you have any idea how we can prevent CloudFlare from breaking saving of objects in the CMS?

**Comment by jakedaleweb** [comment]
@robbieaverill quickest fix would be to configure (in Cloudflare) to not apply any WAF or CDN goodness to any URL starting with /admin - of course this comes with it's risks.

**Comment by robbieaverill** [comment]
@jakedaleweb would it be reasonable to make a rule that doesn't effect `/admin/pages/*` for PSOT requests?

**Comment by robbieaverill** [comment]
Re-tested this in the SilverStripe 4 migration and it's working there. Closing.

**Comment by robbieaverill** [comment]
Although I'll reopen if this happens in production after it's deployed... I suppose we don't use CloudFlare on UAT.
