### ISSUE TITLE
Replace 'clippy' Flash extension

### ISSUE THREAD

**Issue by madmatt** [silverstripe/addons.silverstripe.org#207]
The addon page uses a Flash file to provide 'copy to clipboard' functionality. Lots of other sites do this without Flash (e.g. https://gfycat.com/gifs/detail/FrightenedGreenApe)

~Could we either remove it, or~ implement another option~?~

Sorry for the average report, I hit enter way too early :D

### PR

#214

**Comment by robbieaverill** [comment]
Yes please!

**Comment by robbieaverill** [comment]
Bug, because it's "broken"

**Comment by madmatt** [comment]
Yeah - the copy thing doesn't load in modern browsers by default, they explicitly request you enable Flash for the web page before loading it these days.

**Comment by ScopeyNZ** [comment]
![image](https://user-images.githubusercontent.com/3260989/44497456-77031f80-a6cd-11e8-8d3b-efa7d04f7507.png)

**Comment by brynwhyman** [comment]
Browser support might be a question here. Let's review our list of supported browsers and ensure it will work with all. Fallbacks if required.
