### ISSUE TITLE
Ratings don't appear to be updating

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/addons.silverstripe.org#210]
Example: phptek/verifiable

It's scheduled in jobs, but running the job reports a 404 in Codecov (that's fine) but also zero points overall when the job finishes.

We need to have another look at this. Note there's some other issues e.g. https://github.com/silverstripe/moduleratings/issues/11 and an open pull request to help with diagnosing this kind of problem at #209

**Comment by phptek** [comment]
Well at least the module score is automated now - I thought I still needed to send an email to `cxommunity@silverstripe.org` - indeed, that's what the docs on addons.silverstripe.org still say.

**Comment by phptek** [comment]
Ah, not the same thing as "Module Score" after all. (How _do_ I go about getting one of those?)

**Comment by robbieaverill** [comment]
Has it still not updated!? Well, the PR to add logging for diagnostics was finally merged a couple of days ago so now at least we can work out why the jobs are failing. It should all be automatic

**Comment by phptek** [comment]
Nope. Still says "N/A" :-(

**Comment by robbieaverill** [comment]
@phptek still getting around to looking at fixing this. I've deployed the latest master branch to UAT which includes config for the internal ratings system to send logs to Graylog so we can try and see if there's some rate limiting being hit, or something like that. We'll hopefully be looking at this in the next couple of weeks.

**Comment by robbieaverill** [comment]
Logging is tricky to monitor (see #216). I didn't see anything obvious about the Travis API though. It kind of looks like some jobs aren't being run at all... will keep investigating passively

**Comment by robbieaverill** [comment]
Fixes are at https://github.com/silverstripe/addons.silverstripe.org/pull/217
