### ISSUE TITLE
Upgrade addons.silverstripe.org to SilverStripe 4

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/addons.silverstripe.org#226]
PR #185 covers this work, requires:

- [x] ElasticSearch upgrade on UAT
- [x] Merge of PR #185 to master
- [x] Manual testing of full site / services on UAT
- [ ] Co-ordinated ElasticSearch upgrade on Prod with Prod deployment of SS4 upgrade - https://silverstripe.freshdesk.com/helpdesk/tickets/52224

**Comment by robbieaverill** [comment]
@sminnee I'll look at updating to PHP 7.3 as part of this review

**Comment by robbieaverill** [comment]
Oh wait, you already did that =D

**Comment by robbieaverill** [comment]
Tested, happy, nothing blocking deployment. Ticket blocked until we have ES5 on production though.

**Comment by robbieaverill** [comment]
We don't usually include "deployed" as part of our DOD, so closing as "done" =)
