### ISSUE TITLE
Investigate RDS utilisation

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/addons.silverstripe.org#252]
We've just hit the limit on space in RDS.
As a remediation we increased the server size, but we need to investigate what takes up all the space and optimise.

P.S. as an example, it can be queuedjobDescriptor table

**Comment by robbieaverill** [comment]
It's highly likely to be related to the job queue processing addons every day. This spawns thousands of queued jobs which run regularly. We have run out of disk space on the server before (from cloning addon repositories to analyse them) but the DB is a new one... good luck.

**Comment by chillu** [comment]
I've nuked the `QueuedJobDescriptor`, it had 1m+ rows. Ideally we'd set up https://github.com/symbiote/silverstripe-queuedjobs#configuring-the-cleanupjob, but closing the "investigation" part here
