### ISSUE TITLE
Update to composer v2

### ISSUE THREAD

**Issue by chillu** [silverstripe/addons.silverstripe.org#256]
There seems to be some coupling between running the global `composer` binary/phar, and including the PHP libraries, as evidenced by this build failure: https://travis-ci.com/github/silverstripe/addons.silverstripe.org/builds/202246360#L463. I'm fixing this now via falling back to v1 in `travis.yml`

Functionally, it's unclear how long composer v1 will be supported.

**Comment by robbieaverill** [comment]
We probably need to update those module rating repos to work with Composer 2!

**Comment by chillu** [comment]
PR at https://github.com/silverstripe/addons.silverstripe.org/pull/255, side effect from investigation into OOM errors on prod.

> We probably need to update those module rating repos to work with Composer 2!

Done that now: https://github.com/silverstripe/moduleratings-plugin/pull/2. But I've also removed the dependency from addons, we don't seem to need the *composer plugin*, just `silverstripe/moduleratings` which doesn't have any direct composer dependencies (no upgrade necessary)

**Comment by robbieaverill** [comment]
Yep, you're right. The plugin is there so you can run the module rating commands in the addons project from the command line, if you want to test it.

**Comment by chillu** [comment]
Merged and pushed to prod
