### ISSUE TITLE
Travis build badges still point to travisci.org (is broken)

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/addons.silverstripe.org#266]
All module CI builds have moved out of travis-ci.org and on to travis-ci**.com** (after their .org service was shutdown).

The build badges captured in the following page still point to the 'travis-ci.org' builds, which no longer run. That's giving a false report of how the builds for each module is doing. See: https://www.silverstripe.org/software/addons/silverstripe-commercially-supported-module-list/

We could update the badges to point to the new builds in travis-ci.com, or...

I'm personally wary of this information being provided here, as I don't think it provides a whole lot of additional value to visitors of the page. Sure, as a developer wanting to know about supported modules it's nice to know if the CI builds are passing, but as a baseline they should always be passing and the team behind the maintenance have other ways to stay accountable to this. As an aside, there's plans to drop the Scrutinizer service which is another badge.

**Comment by brynwhyman** [comment]
Other places to see build status:
* https://emtek.net.nz/rhino/tables?t=builds
* https://maxime-rainville.github.io/travis-dashboard/

**Comment by GuySartorelli** [comment]
Related PR: silverstripe/moduleratings#20

**Comment by emteknetnz** [comment]
Module list has be previously updated to use github actions badges
