### ISSUE TITLE
Addons data not updating

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/addons.silverstripe.org#268]
Addons site is not pulling in package data updates.

Example: https://addons.silverstripe.org/add-ons/innoweb/silverstripe-international-phone-number-field

**Comment by xini** [comment]
It looks like tags etc are pulled through regularly, but not the readme? 
For https://addons.silverstripe.org/add-ons/innoweb/silverstripe-international-phone-number-field, the readme has not been updated for at least 6 months (commit https://github.com/xini/silverstripe-international-phone-number-field/commit/858596705cf7db1b1948f189bb31a8e5371d0e7d).

**Comment by xini** [comment]
@maxime-rainville any updates on this? Cheers

**Comment by maxime-rainville** [comment]
We're nuking this in the DOtOrg rebuild.

**Comment by xini** [comment]
a) this is not completed
b) who decided that addons is going to be discontinued?
