### ISSUE TITLE
Addons with a fullstop/file extension in the name cause a 404 error

### ISSUE THREAD

**Issue by camfindlay** [silverstripe/addons.silverstripe.org#81]
See http://addons.silverstripe.org/add-ons/axllent/silverstripe-analytics.js/

This is a legit addon however it's listing doesn't show as I think the addons site is interpreting the.js as a file rather than a url segment.

**Comment by brynwhyman** [comment]
I think there's a typo in URL you've referenced, or the repo name has changed. The repository is: `axllent/silverstripe-analytics-js` (no fullstop).

This link works: https://addons.silverstripe.org/add-ons/axllent/silverstripe-analytics-js

Closing :)
