### ISSUE TITLE
2.4 filter option unusable (legacy link)

### ISSUE THREAD

**Issue by muskie9** [silverstripe/addons.silverstripe.org#85]
When using the 2.4 filter option we get the message to use the legacy database. When following the link you're redirected to the addons home page. I know we're going to the .org site where the modules used to live and that's the actual redirector so wasn't sure where to document this.

**Comment by muskie9** [comment]
Is there some place to find the old 2.4 modules list? I have a couple sites that aren't quite to 3.x and hoped to find some of the older modules.

**Comment by camfindlay** [comment]
Old 2.4 modules can have composer files - the list on ss.org is not longer a thing (and hasn't been for some time). I'll be removing the message with old link as it's confusing now that 2.4 is EOL.
