### ISSUE TITLE
Hosting for module documentation

### ISSUE THREAD

**Issue by jedateach** [silverstripe/addons.silverstripe.org#89]
Documentation is an important part of the modules (themes?) ecosystem. Good documentation will help devs get up and running quick, troubleshoot issues, and it will also help end-users to use the additional features/functionality they bring to SilverStripe.

A docs hosting service will take the headache out of maintainers needing to set up hosting.
It also will help devs when gauging the quality of a module.

This probably only applies to larger modules that require more than a README page.
#### Per-site custom user docs

Hosting documentation for modules could open the door for the CMS "help" link to link through to documentation that is specific to the current install. Perhaps links like `http://userhelp.silverstripe.org/?modules=framework-3.1,cms-3.1,shop-1.0,blog-0.7` could be used.

**Comment by jedateach** [comment]
I guess there is a bit of complexity introduced with versions.

**Comment by jedateach** [comment]
An alternative to SS hosting could be to encourage getting docs onto https://readthedocs.org/ . I think it would be better to group docs in one location however.

**Comment by robbieaverill** [comment]
Interesting idea. Do you have plans for this still?

**Comment by jedateach** [comment]
No I don't sorry.
